services:
  db:
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  ui:
    build: ui/
    ports: 
      - "5173:5173"
  api:
    build: api/
    ports:
      - "8080:8080"
